### ISSUE TITLE
Digestif

### ISSUE THREAD

**Issue by linwaytin** [langserver/langserver.github.io#185]
Digestif is an LSP server for LaTeX.
https://github.com/astoff/digestif

**Comment by keegancsmith** [comment]
Hi @linwaytin, could you open a PR adding it?

**Comment by linwaytin** [comment]
How can I do that?

**Comment by keegancsmith** [comment]
If you are unfamiliar with creating pull requests / HTML but want to try, try and copy the change that was done in a closed PR https://github.com/langserver/langserver.github.io/pulls?q=is%3Apr+is%3Aclosed

You can do it from GitHub https://github.com/langserver/langserver.github.io/edit/master/index.html

Otherwise I can add in the details for you.

**Comment by linwaytin** [comment]
Hi @keegancsmith,
Yes I'm not familiar with pull requests, and do not have time to try it now.
It will be nice if you can add them.
Thank you.
